name: Deploy Next.js Standalone to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare deployment
        run: |
          rm -rf deploy
          mkdir deploy

          # copy standalone server AS ROOT server.js
          cp .next/standalone/server.js deploy/server.js

          # copy required runtime files
          cp -r .next/standalone/. deploy/.next/
          cp -r .next/static deploy/.next/
          cp -r public deploy/
          cp package.json deploy/

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: CloudHosting
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy
